name: Deploy to UAT

on:
  workflow_dispatch:

jobs:
  deploy-to-uat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Service
        run: |
          docker-compose -f ./src/BlackList.Api/docker-compose.yml up -d --build

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "blacklist-faceit-service-uat"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true